# Generated by Django 2.2.11 on 2021-08-04 18:53

import crud.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_updatedat',
            field=crud.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='user_created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
