# Generated by Django 2.2.11 on 2021-08-04 18:56

import crud.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210805_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_updatedat',
            field=crud.models.AutoDateTimeField(default=datetime.datetime(2021, 8, 4, 18, 56, 53, 115636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 18, 56, 53, 115636, tzinfo=utc)),
        ),
    ]
